package newstime.fronteira;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import newstime.controle.ControleAdministracao;
import newstime.excecao.BancoException;
import newstime.excecao.NegocioException;

/**
 * Classe do formulário de CRUD do livro
 * @author lukin
 */
public class CadastroLivro extends javax.swing.JFrame {

    /**
     * Creates new form CadastroLivro
     */
    private boolean oferta = false, digital = false;//variaveis para radio buton

    public CadastroLivro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nomeAutor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_titulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_editora = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmb_categoria = new javax.swing.JComboBox<String>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_resumo = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_sumario = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        rdo_digitalSim = new javax.swing.JRadioButton();
        rdo_digitalNao = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        rdo_ofertSim = new javax.swing.JRadioButton();
        rdo_ofertaNao = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        txt_numPaginas = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_precoRevenda = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_precoOferta = new javax.swing.JTextField();
        cmb_margemLucro = new javax.swing.JComboBox<String>();
        btn_pesquisar = new javax.swing.JButton();
        btn_alterar = new javax.swing.JButton();
        btn_cadastrar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        cmb_dia = new javax.swing.JComboBox<String>();
        cmb_mes = new javax.swing.JComboBox<String>();
        cmb_ano = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_qtd = new javax.swing.JFormattedTextField();
        txt_isbn = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_precoCusto = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        cmb_formato = new javax.swing.JComboBox<String>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Broadway", 0, 18)); // NOI18N
        jLabel1.setText("Livros");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Broadway", 0, 12)); // NOI18N
        jLabel2.setText("Nome do Autor");

        jLabel3.setFont(new java.awt.Font("Broadway", 0, 12)); // NOI18N
        jLabel3.setText("Título");

        jLabel4.setFont(new java.awt.Font("Broadway", 0, 12)); // NOI18N
        jLabel4.setText("Editora");

        jLabel5.setFont(new java.awt.Font("Broadway", 0, 11)); // NOI18N
        jLabel5.setText("Ano de Publicação");

        jLabel7.setFont(new java.awt.Font("Broadway", 0, 12)); // NOI18N
        jLabel7.setText("Categoria");

        cmb_categoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione..", "ADMINISTRACAO", "AGROPECUARIA", "ARTES", "AUDIOLIVRO", "AUTOAJUDA", "CIENCIAS_BIO", "CIENCIAS_EXA", "CIENCIAS_HUM", "CONTABILIDADE", "IDIOMA", "DICIONARIO", "DIDATICO", "DIREITO", "ECONOMIA", "ENG_TEC", "ESPORTE", "GASTRONOMIA", "GEO_HIST", "INFORMATICA", "LINGUISTICA", "LITER_ESTR", "LITER_INFA", "LITER_NACIO", "MEDICINA", "RELIGIAO", "TURISMO" }));

        jLabel8.setFont(new java.awt.Font("Broadway", 0, 12)); // NOI18N
        jLabel8.setText("ISBN");

        jLabel9.setFont(new java.awt.Font("Broadway", 0, 12)); // NOI18N
        jLabel9.setText("Quantidade");

        jLabel10.setFont(new java.awt.Font("Broadway", 0, 11)); // NOI18N
        jLabel10.setText("Resumo");

        txt_resumo.setColumns(20);
        txt_resumo.setRows(5);
        jScrollPane1.setViewportView(txt_resumo);

        jLabel11.setFont(new java.awt.Font("Broadway", 0, 11)); // NOI18N
        jLabel11.setText("Sumário");

        txt_sumario.setColumns(20);
        txt_sumario.setRows(5);
        jScrollPane2.setViewportView(txt_sumario);

        jLabel12.setFont(new java.awt.Font("Broadway", 0, 12)); // NOI18N
        jLabel12.setText("Formato do livro");

        buttonGroup1.add(rdo_digitalSim);
        rdo_digitalSim.setText("Sim");
        rdo_digitalSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_digitalSimActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdo_digitalNao);
        rdo_digitalNao.setSelected(true);
        rdo_digitalNao.setText("Não");
        rdo_digitalNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_digitalNaoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Broadway", 0, 12)); // NOI18N
        jLabel13.setText("Oferta");

        buttonGroup2.add(rdo_ofertSim);
        rdo_ofertSim.setText("Sim");
        rdo_ofertSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_ofertSimActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdo_ofertaNao);
        rdo_ofertaNao.setSelected(true);
        rdo_ofertaNao.setText("Não");
        rdo_ofertaNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_ofertaNaoActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Broadway", 0, 12)); // NOI18N
        jLabel14.setText("Livro Digital");

        jLabel15.setFont(new java.awt.Font("Broadway", 0, 12)); // NOI18N
        jLabel15.setText("Margem de Lucro");

        jLabel16.setFont(new java.awt.Font("Broadway", 0, 12)); // NOI18N
        jLabel16.setText("Preço para Revenda");

        jLabel17.setFont(new java.awt.Font("Broadway", 0, 12)); // NOI18N
        jLabel17.setText("Preço de Oferta");

        cmb_margemLucro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione..", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100" }));

        btn_pesquisar.setText("Pesquisar");
        btn_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarActionPerformed(evt);
            }
        });

        btn_alterar.setText("Alterar");
        btn_alterar.setEnabled(false);
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        btn_excluir.setText("Excluir");
        btn_excluir.setEnabled(false);
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        jLabel18.setText("%");

        jButton5.setText("Limpar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        cmb_dia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cmb_mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        cmb_ano.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016" }));
        cmb_ano.setSelectedIndex(50);
        cmb_ano.setToolTipText("");
        cmb_ano.setAutoscrolls(true);

        jLabel6.setText("/");

        jLabel19.setText("/");

        txt_qtd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("######"))));

        jLabel20.setFont(new java.awt.Font("Broadway", 0, 12)); // NOI18N
        jLabel20.setText("Preço de Custo");

        jLabel21.setFont(new java.awt.Font("Broadway", 0, 12)); // NOI18N
        jLabel21.setText("Número de páginas");

        cmb_formato.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione..", "BROCHURA", "GRAMPO", "CAPA_DURA", "DIGITAL" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdo_ofertSim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdo_ofertaNao))
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdo_digitalSim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdo_digitalNao)))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmb_margemLucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18))
                            .addComponent(jLabel20)
                            .addComponent(txt_precoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_numPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(cmb_formato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)
                                .addGap(44, 44, 44)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_precoOferta, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_precoRevenda, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(6, 6, 6)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_nomeAutor)
                                    .addComponent(txt_titulo)
                                    .addComponent(txt_editora, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(cmb_dia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmb_mes, 0, 65, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmb_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmb_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap(36, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nomeAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_editora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(cmb_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(txt_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_precoRevenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_numPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_precoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_precoOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_formato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cmb_margemLucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel18)))
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdo_digitalSim)
                                    .addComponent(rdo_digitalNao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdo_ofertSim)
                                    .addComponent(rdo_ofertaNao))))
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_pesquisar)
                    .addComponent(btn_alterar)
                    .addComponent(btn_excluir)
                    .addComponent(btn_cadastrar)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdo_digitalSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_digitalSimActionPerformed
        digital = true;
    }//GEN-LAST:event_rdo_digitalSimActionPerformed

    private void rdo_digitalNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_digitalNaoActionPerformed
        digital = false;
    }//GEN-LAST:event_rdo_digitalNaoActionPerformed

    private void rdo_ofertSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_ofertSimActionPerformed
        //System.out.println("Sim");
        oferta = true;
    }//GEN-LAST:event_rdo_ofertSimActionPerformed

    private void rdo_ofertaNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_ofertaNaoActionPerformed
        //System.out.println("Nao");
        oferta = false;
    }//GEN-LAST:event_rdo_ofertaNaoActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        //Verifica os campos
        if ("".equals(txt_isbn.getText()) || "".equals(txt_titulo.getText()) || "".equals(txt_nomeAutor.getText()) ||
                "".equals(txt_editora.getText()) || "Selecione..".equals(cmb_categoria.getSelectedItem().toString()) ||
                "".equals(txt_resumo.getText()) || "".equals(txt_sumario.getText()) || "".equals(txt_qtd.getText()) ||
                "Selecione..".equals(cmb_margemLucro.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Há campos não preenchidos.");
            return;
        }
        //Cadastra
        ControleAdministracao controleAdm = new ControleAdministracao();
        try {
            String data = cmb_dia.getSelectedItem().toString() + cmb_mes.getSelectedItem().toString() + cmb_ano.getSelectedItem().toString();
            controleAdm.inserirLivro(txt_isbn.getText(), txt_titulo.getText(), txt_nomeAutor.getText(), txt_editora.getText(), data, cmb_categoria.getSelectedItem().toString(), txt_resumo.getText(), txt_sumario.getText(),  cmb_formato.getSelectedItem().toString(), txt_numPaginas.getText(), txt_qtd.getText(), txt_precoRevenda.getText(), txt_precoOferta.getText(), txt_numPaginas.getText(), cmb_margemLucro.getSelectedItem().toString(), oferta, digital);
            JOptionPane.showMessageDialog(null, "O livro foi cadastrado com sucesso.");
            limparCampos();
        } catch (BancoException | NegocioException ex) {
            JOptionPane.showMessageDialog(null,"O livro não foi cadastrado: " + ex.toString());
        }
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarActionPerformed
        //Verifica o campo ISBN
        if ("".equals(txt_isbn.getText()) || " ".equals(txt_isbn.getText()) || "  ".equals(txt_isbn.getText()) ||
                "    ".equals(txt_isbn.getText()) || "     ".equals(txt_isbn.getText()) ||
                "       ".equals(txt_isbn.getText()) || "      ".equals(txt_isbn.getText()) ||
                "      ".equals(txt_isbn.getText()) || "            ".equals(txt_isbn.getText()) ||
                "            ".equals(txt_isbn.getText()) || "           ".equals(txt_isbn.getText()) ||
                "          ".equals(txt_isbn.getText()) || "         ".equals(txt_isbn.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Informe o ISBN para buscar.");
            txt_isbn.requestFocus();
            return;
        }
        //Pesquisa
        ControleAdministracao controleAdm = new ControleAdministracao();
        try {
            controleAdm.buscarLivro(txt_isbn.getText());
            txt_isbn.setEnabled(false);
            
            txt_titulo.setText(controleAdm.getTitulo());
            txt_nomeAutor.setText(controleAdm.getNomeAutor());
            txt_editora.setText(controleAdm.getNomeEditora());
            cmb_dia.setSelectedItem("01"); //Alterar (?)
            cmb_mes.setSelectedItem("01"); //Alterar (?)
            cmb_ano.setSelectedItem(String.valueOf(controleAdm.getAnoPublicacao()));
            cmb_categoria.setSelectedItem(controleAdm.getCategoria());
            txt_resumo.setText(controleAdm.getResumo());
            txt_sumario.setText(controleAdm.getSumario());
            txt_qtd.setText(String.valueOf(controleAdm.getQtdEstoque()));
            txt_precoCusto.setText(String.valueOf(controleAdm.getPrecoCusto()));
            txt_precoRevenda.setText(String.valueOf(controleAdm.getPrecoVenda()));
            txt_precoOferta.setText(String.valueOf(controleAdm.getPrecoOferta()));
            txt_numPaginas.setText(String.valueOf(controleAdm.getNumPaginas()));
            cmb_formato.setSelectedItem(controleAdm.getFormato());
            cmb_margemLucro.setSelectedItem(controleAdm.getMargemLucro());
            rdo_digitalNao.setSelected(controleAdm.isDigital());
            rdo_ofertaNao.setSelected(controleAdm.isOferta());
            
            liberaBotao();
        } catch (BancoException ex) {
            JOptionPane.showMessageDialog(null,"O livro não foi encontrado: " + ex.getMessage());
        }
    }//GEN-LAST:event_btn_pesquisarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        limparCampos();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        //Verifica o campo ISBN
        if ("".equals(txt_isbn.getText()) || " ".equals(txt_isbn.getText()) || "  ".equals(txt_isbn.getText()) ||
                "    ".equals(txt_isbn.getText()) || "     ".equals(txt_isbn.getText()) ||
                "       ".equals(txt_isbn.getText()) || "      ".equals(txt_isbn.getText()) ||
                "      ".equals(txt_isbn.getText()) || "            ".equals(txt_isbn.getText()) ||
                "            ".equals(txt_isbn.getText()) || "           ".equals(txt_isbn.getText()) ||
                "          ".equals(txt_isbn.getText()) || "         ".equals(txt_isbn.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Informe o ISBN para excluir.");
            txt_isbn.requestFocus();
            return;
        }
        //Certifica ação, retornando caso cancele
        if(JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o livro?") != JOptionPane.YES_OPTION) {
            return;
        }
        //Exclui
        ControleAdministracao adm = new ControleAdministracao();
        try {
            adm.removerLivro(txt_isbn.getText());
            txt_isbn.setEditable(true);
            JOptionPane.showMessageDialog(null,"O livro foi excluído com sucesso.");
            limparCampos();
        } catch (BancoException ex) {
            JOptionPane.showMessageDialog(null,"O livro não foi excluído: " + ex.getMessage());
        }        
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        //Verifica os campos
        if ("".equals(txt_isbn.getText()) || "".equals(txt_titulo.getText()) || "".equals(txt_nomeAutor.getText()) ||
                "".equals(txt_editora.getText()) || "Selecione..".equals(cmb_categoria.getSelectedItem().toString()) ||
                "".equals(txt_resumo.getText()) || "".equals(txt_sumario.getText()) || "".equals(txt_qtd.getText()) ||
                "Selecione..".equals(cmb_margemLucro.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Há campos não preenchidos.");
            return;
        }
        //Altera
        ControleAdministracao adm = new ControleAdministracao();
        try {
            String data = cmb_dia.getSelectedItem().toString() + cmb_mes.getSelectedItem().toString() + cmb_ano.getSelectedItem().toString();
            adm.alterarLivro(txt_isbn.getText(), txt_titulo.getText(), txt_nomeAutor.getText(), txt_editora.getText(), data, cmb_categoria.getSelectedItem().toString(), txt_resumo.getText(), txt_sumario.getText(), cmb_formato.getSelectedItem().toString(), txt_numPaginas.getText(), txt_qtd.getText(), txt_precoRevenda.getText(), txt_precoOferta.getText(), txt_numPaginas.getText(), cmb_margemLucro.getSelectedItem().toString(), oferta, digital);
            JOptionPane.showMessageDialog(null, "O livro foi alterado com sucesso.");
            txt_isbn.setEditable(true);
            limparCampos();
        } catch (BancoException | NegocioException ex) {
            JOptionPane.showMessageDialog(null,"O livro não foi alterado: " + ex.toString());
        }
    }//GEN-LAST:event_btn_alterarActionPerformed
    
    public void limparCampos() {
        txt_isbn.setText("");
        txt_titulo.setText("");
        txt_nomeAutor.setText("");
        txt_editora.setText("");
        cmb_dia.setSelectedItem("01");
        cmb_mes.setSelectedItem("01");
        cmb_ano.setSelectedItem("1950");
        cmb_categoria.setSelectedItem("Selecione..");
        txt_resumo.setText("");
        txt_sumario.setText("");
        txt_qtd.setText("");
        txt_precoCusto.setText("");
        txt_precoRevenda.setText("");
        txt_precoOferta.setText("");
        txt_numPaginas.setText("");
        cmb_margemLucro.setSelectedItem("Selecione..");
        cmb_formato.setSelectedItem("Selecione..");
        oferta = false;
        digital = false;
        rdo_digitalNao.setSelected(false);
        rdo_ofertaNao.setSelected(false);
        
        txt_isbn.setEnabled(true);
        bloqueiaBotao();
    }

    public void liberaBotao() {
        btn_alterar.setEnabled(true);
        btn_excluir.setEnabled(true);
    }

    public void bloqueiaBotao() {
        btn_alterar.setEnabled(false);
        btn_excluir.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CadastroLivro().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_pesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmb_ano;
    private javax.swing.JComboBox<String> cmb_categoria;
    private javax.swing.JComboBox<String> cmb_dia;
    private javax.swing.JComboBox<String> cmb_formato;
    private javax.swing.JComboBox<String> cmb_margemLucro;
    private javax.swing.JComboBox<String> cmb_mes;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdo_digitalNao;
    private javax.swing.JRadioButton rdo_digitalSim;
    private javax.swing.JRadioButton rdo_ofertSim;
    private javax.swing.JRadioButton rdo_ofertaNao;
    private javax.swing.JTextField txt_editora;
    private javax.swing.JTextField txt_isbn;
    private javax.swing.JTextField txt_nomeAutor;
    private javax.swing.JTextField txt_numPaginas;
    private javax.swing.JTextField txt_precoCusto;
    private javax.swing.JTextField txt_precoOferta;
    private javax.swing.JTextField txt_precoRevenda;
    private javax.swing.JFormattedTextField txt_qtd;
    private javax.swing.JTextArea txt_resumo;
    private javax.swing.JTextArea txt_sumario;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
